#include "platform/RenderAPI.h"
#include "switch/render/SwitchGraphicsContext.h"
#include <glad/glad.h>
#include <algorithm>
#include <cstring>
namespace { int viewport[4]={0,0,1280,720}; }
namespace { GLenum capability(RenderCapability c){switch(c){case RenderCapability::CullFace:return GL_CULL_FACE;case RenderCapability::Blend:return GL_BLEND;case RenderCapability::DepthTest:return GL_DEPTH_TEST;case RenderCapability::PolygonOffsetFill:return GL_POLYGON_OFFSET_FILL;default:return 0;}} GLenum blend(RenderBlendFactor f){switch(f){case RenderBlendFactor::Zero:return GL_ZERO;case RenderBlendFactor::One:return GL_ONE;case RenderBlendFactor::SrcColor:return GL_SRC_COLOR;case RenderBlendFactor::OneMinusSrcColor:return GL_ONE_MINUS_SRC_COLOR;case RenderBlendFactor::SrcAlpha:return GL_SRC_ALPHA;case RenderBlendFactor::OneMinusSrcAlpha:return GL_ONE_MINUS_SRC_ALPHA;case RenderBlendFactor::DstAlpha:return GL_DST_ALPHA;case RenderBlendFactor::OneMinusDstAlpha:return GL_ONE_MINUS_DST_ALPHA;case RenderBlendFactor::DstColor:return GL_DST_COLOR;case RenderBlendFactor::OneMinusDstColor:return GL_ONE_MINUS_DST_COLOR;}return GL_ONE;}}
void renderEnable(RenderCapability c){const GLenum value=capability(c);if(value)glEnable(value);} void renderDisable(RenderCapability c){const GLenum value=capability(c);if(value)glDisable(value);} void renderBlendFunc(RenderBlendFactor source,RenderBlendFactor dest){glBlendFunc(blend(source),blend(dest));} void renderDepthMask(bool enabled){glDepthMask(enabled?GL_TRUE:GL_FALSE);} void renderDepthFunc(RenderCompare){} void renderAlphaFunc(RenderCompare,float){} void renderCullFace(RenderFace face){glCullFace(face==RenderFace::Front?GL_FRONT:face==RenderFace::Back?GL_BACK:GL_FRONT_AND_BACK);} void renderColorMask(bool r,bool g,bool b,bool a){glColorMask(r,g,b,a);} void renderBindTexture(int texture){glBindTexture(GL_TEXTURE_2D,static_cast<GLuint>(texture));} void renderSetActiveTextureUnit(int unit){glActiveTexture(GL_TEXTURE0+unit);} void renderSetClientActiveTextureUnit(int){} void renderSetMultiTextureCoord(int,float,float){} void renderSetLightmapColors(const std::uint32_t*,int){} void renderColor4f(float,float,float,float){} void renderColor3f(float,float,float){} void renderNormal3f(float,float,float){}
void renderGenerateTextures(int n,int*t){glGenTextures(n,reinterpret_cast<GLuint*>(t));} void renderDeleteTextures(int n,const int*t){glDeleteTextures(n,reinterpret_cast<const GLuint*>(t));} void renderTextureSubImageRgba(int level,int x,int y,int w,int h,const void*p){glTexSubImage2D(GL_TEXTURE_2D,level,x,y,w,h,GL_RGBA,GL_UNSIGNED_BYTE,p);} void renderTextureImageRgba(int level,int w,int h,const void*p){glTexImage2D(GL_TEXTURE_2D,level,GL_RGBA8,w,h,0,GL_RGBA,GL_UNSIGNED_BYTE,p);} void renderTextureParameters(bool blur,bool clamp,bool mipmaps){glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,mipmaps?(blur?GL_LINEAR_MIPMAP_LINEAR:GL_NEAREST_MIPMAP_LINEAR):(blur?GL_LINEAR:GL_NEAREST));glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,blur?GL_LINEAR:GL_NEAREST);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,clamp?GL_CLAMP_TO_EDGE:GL_REPEAT);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,clamp?GL_CLAMP_TO_EDGE:GL_REPEAT);}
#include <algorithm>
#include <cstring>
namespace { int nextTexture=1; int viewport[4]={0,0,1280,720}; float clearColor[4]={0,0,0,1}; const unsigned char vendor[]="libnx native framebuffer"; }
#define NOOP1(name,T) void name(T){}
void renderEnable(RenderCapability){} void renderDisable(RenderCapability){} void renderBlendFunc(RenderBlendFactor,RenderBlendFactor){} void renderDepthMask(bool){} void renderDepthFunc(RenderCompare){} void renderAlphaFunc(RenderCompare,float){} void renderCullFace(RenderFace){} void renderColorMask(bool,bool,bool,bool){} void renderBindTexture(int){} void renderSetActiveTextureUnit(int){} void renderSetClientActiveTextureUnit(int){} void renderSetMultiTextureCoord(int,float,float){} void renderSetLightmapColors(const std::uint32_t*,int){} void renderColor4f(float,float,float,float){} void renderColor3f(float,float,float){} void renderNormal3f(float,float,float){}
void renderGenerateTextures(int n,int*t){while(n--)*t++=nextTexture++;} void renderDeleteTextures(int,const int*){} void renderTextureSubImageRgba(int,int,int,int,int,const void*){} void renderTextureImageRgba(int,int,int,const void*){} void renderTextureParameters(bool,bool,bool){}
#if PLATFORM_TEXTURE_QUALITY_CONTROLS
void renderApplyTextureQuality(bool,int,bool,int){}
#endif
int renderGetMaxAnisotropy(){return 1;} int renderGetMaxSamples(){return 1;} bool renderTextureBeginUpload(int,int,int,int,bool,bool,bool,bool){return true;} bool renderTextureIsValid(int t){return t>0;} void renderResetResources(){} void renderFogf(RenderFogParameter,float){} void renderFogi(RenderFogParameter,RenderFogMode){} void renderFogColor(const float*){} void renderLightfv(int,RenderLightParameter,const float*){} void renderLightModelAmbient(const float*){} void renderColorMaterial(RenderFace,RenderColorMaterialMode){} void renderShadeModel(RenderShadeModel){}
void renderClear(unsigned int mask){GLbitfield bits=0;if(mask&RenderClearMask::Color)bits|=GL_COLOR_BUFFER_BIT;if(mask&RenderClearMask::Depth)bits|=GL_DEPTH_BUFFER_BIT;if(bits)glClear(bits);} void renderFinishGpu(){glFinish();} void renderSubmitFrame(){glFlush();} void renderClearColor(float r,float g,float b,float a){glClearColor(r,g,b,a);} void renderClearDepth(double d){glClearDepth(d);} void renderPolygonOffset(float factor,float units){glPolygonOffset(factor,units);} void renderLineWidth(float width){glLineWidth(width);} void renderViewport(int x,int y,int w,int h){viewport[0]=x;viewport[1]=y;viewport[2]=w;viewport[3]=h;glViewport(x,y,w,h);} void renderGetViewport(int*v){glGetIntegerv(GL_VIEWPORT,v);}
void renderGetMatrix(RenderMatrixQuery,float*v){std::fill(v,v+16,0.f);v[0]=v[5]=v[10]=v[15]=1.f;} const unsigned char* renderGetString(RenderStringQuery query){GLenum name=GL_VENDOR;if(query==RenderStringQuery::Renderer)name=GL_RENDERER;else if(query==RenderStringQuery::Version)name=GL_VERSION;else if(query==RenderStringQuery::Extensions)name=GL_EXTENSIONS;return glGetString(name);} bool renderSupportsFeature(RenderFeature){return false;} unsigned int renderGetError(){return glGetError();} void renderFogHint(RenderHintMode){} void renderMatrixMode(RenderMatrixMode){} void renderLoadIdentity(){} void renderPushMatrix(){} void renderPopMatrix(){} void renderTranslate(float,float,float){} void renderRotate(float,float,float,float){} void renderScale(float,float,float){} void renderScaleDouble(double,double,double){} void renderFrustum(double,double,double,double,double,double){} void renderOrtho(double,double,double,double,double,double){}
bool renderCopyFramebufferToBoundTexture(int x,int y,int w,int h){if(w<=0||h<=0)return false;glCopyTexSubImage2D(GL_TEXTURE_2D,0,0,0,x,y,w,h);return glGetError()==GL_NO_ERROR;} void renderSetLegacyPresentationGamma(bool){}
void renderClear(unsigned int mask){if(!(mask&RenderClearMask::Color))return;auto*p=SwitchGraphicsContext::instance().pixels();if(!p)return;auto cv=[](float f){return(unsigned)(std::max(0.f,std::min(1.f,f))*255.f);};std::uint32_t c=cv(clearColor[0])|(cv(clearColor[1])<<8)|(cv(clearColor[2])<<16)|(cv(clearColor[3])<<24);std::fill(p,p+1280*720,c);} void renderFinishGpu(){} void renderSubmitFrame(){} void renderClearColor(float r,float g,float b,float a){clearColor[0]=r;clearColor[1]=g;clearColor[2]=b;clearColor[3]=a;} void renderClearDepth(double){} void renderPolygonOffset(float,float){} void renderLineWidth(float){} void renderViewport(int x,int y,int w,int h){viewport[0]=x;viewport[1]=y;viewport[2]=w;viewport[3]=h;} void renderGetViewport(int*v){std::memcpy(v,viewport,sizeof(viewport));}
void renderGetMatrix(RenderMatrixQuery,float*v){std::fill(v,v+16,0.f);v[0]=v[5]=v[10]=v[15]=1.f;} const unsigned char* renderGetString(RenderStringQuery){return vendor;} bool renderSupportsFeature(RenderFeature){return false;} unsigned int renderGetError(){return 0;} void renderFogHint(RenderHintMode){} void renderMatrixMode(RenderMatrixMode){} void renderLoadIdentity(){} void renderPushMatrix(){} void renderPopMatrix(){} void renderTranslate(float,float,float){} void renderRotate(float,float,float,float){} void renderScale(float,float,float){} void renderScaleDouble(double,double,double){} void renderFrustum(double,double,double,double,double,double){} void renderOrtho(double,double,double,double,double,double){}
bool renderCopyFramebufferToBoundTexture(int,int,int,int){return false;} void renderSetLegacyPresentationGamma(bool){}
bool renderDrawInterleaved(const RenderInterleavedMesh&m){return m.data&&m.count>0;} bool renderCaptureInterleaved(const RenderInterleavedMesh&m,RenderCapturedMesh&o,bool append){if(!m.data||m.count<=0||m.stride<=0)return false;if(!append)o.clear();const auto*n=(const std::int32_t*)m.data;std::size_t words=(std::size_t)m.count*m.stride/4;o.raw.insert(o.raw.end(),n,n+words);o.vertexCount+=m.count;o.stride=m.stride;o.primitive=m.primitive;o.positionShort=m.positionShort;o.hasTexture=m.hasTexture;o.texCoordOffset=m.texCoordOffset;o.hasColor=m.hasColor;o.colorOffset=m.colorOffset;o.hasNormals=m.hasNormals;o.normalOffset=m.normalOffset;o.hasBrightness=m.hasBrightness;o.brightnessOffset=m.brightnessOffset;return true;} bool renderDrawCaptured(const RenderCapturedMesh&m){return !m.empty();}

// The shared renderer still uses legacy retained handles for sky and chunk
// bookkeeping. Keep a handle namespace until the Switch terrain renderer owns
// those meshes directly; no desktop GL implementation is pulled into the NRO.
namespace { int nextDisplayList = 1; int nextQuery = 1; }
int renderGenerateDisplayLists(int count){const int first=nextDisplayList;nextDisplayList+=count;return first;}
void renderDeleteDisplayLists(int,int){} void renderBeginDisplayList(int){} void renderEndDisplayList(){}
void renderCallDisplayList(int){} void renderCallDisplayLists(int,const int*){}
void renderGenerateOcclusionQueries(int count,int* queries){while(count--)*queries++=nextQuery++;}
void renderBeginOcclusionQuery(int){} void renderEndOcclusionQuery(){}
bool renderOcclusionQueryResultAvailable(int){return true;} unsigned int renderOcclusionQueryResult(int){return 1;}
bool renderReadPixelsRgb(int x,int y,int w,int h,void*p){if(!p||w<=0||h<=0)return false;glPixelStorei(GL_PACK_ALIGNMENT,1);glReadPixels(x,y,w,h,GL_RGB,GL_UNSIGNED_BYTE,p);return glGetError()==GL_NO_ERROR;}
bool renderReadPixelsRgb(int,int,int,int,void*){return false;}
void renderClear(unsigned int mask){if(!(mask&RenderClearMask::Color))return;auto*p=SwitchGraphicsContext::instance().pixels();if(!p)return;auto cv=[](float f){return(unsigned)(std::max(0.f,std::min(1.f,f))*255.f);};std::uint32_t c=cv(clearColor[0])|(cv(clearColor[1])<<8)|(cv(clearColor[2])<<16)|(cv(clearColor[3])<<24);std::fill(p,p+1280*720,c);} void renderFinishGpu(){} void renderSubmitFrame(){SwitchGraphicsContext::instance().present();} void renderClearColor(float r,float g,float b,float a){clearColor[0]=r;clearColor[1]=g;clearColor[2]=b;clearColor[3]=a;} void renderClearDepth(double){} void renderPolygonOffset(float,float){} void renderLineWidth(float){} void renderViewport(int x,int y,int w,int h){viewport[0]=x;viewport[1]=y;viewport[2]=w;viewport[3]=h;} void renderGetViewport(int*v){std::memcpy(v,viewport,sizeof(viewport));}
void renderGetMatrix(RenderMatrixQuery,float*v){std::fill(v,v+16,0.f);v[0]=v[5]=v[10]=v[15]=1.f;} const unsigned char* renderGetString(RenderStringQuery){return vendor;} bool renderSupportsFeature(RenderFeature){return false;} unsigned int renderGetError(){return 0;} void renderFogHint(RenderHintMode){} void renderMatrixMode(RenderMatrixMode){} void renderLoadIdentity(){} void renderPushMatrix(){} void renderPopMatrix(){} void renderTranslate(float,float,float){} void renderRotate(float,float,float,float){} void renderScale(float,float,float){} void renderScaleDouble(double,double,double){} void renderFrustum(double,double,double,double,double,double){} void renderOrtho(double,double,double,double,double,double){}
bool renderCopyFramebufferToBoundTexture(int,int,int,int){return false;} void renderSetLegacyPresentationGamma(bool){}
bool renderDrawInterleaved(const RenderInterleavedMesh&m){return m.data&&m.count>0;} bool renderCaptureInterleaved(const RenderInterleavedMesh&m,RenderCapturedMesh&o,bool append){if(!m.data||m.count<=0||m.stride<=0)return false;if(!append)o.clear();const auto*n=(const std::int32_t*)m.data;std::size_t words=(std::size_t)m.count*m.stride/4;o.raw.insert(o.raw.end(),n,n+words);o.vertexCount+=m.count;o.stride=m.stride;o.primitive=m.primitive;o.positionShort=m.positionShort;o.hasTexture=m.hasTexture;o.texCoordOffset=m.texCoordOffset;o.hasColor=m.hasColor;o.colorOffset=m.colorOffset;o.hasNormals=m.hasNormals;o.normalOffset=m.normalOffset;o.hasBrightness=m.hasBrightness;o.brightnessOffset=m.brightnessOffset;return true;} bool renderDrawCaptured(const RenderCapturedMesh&m){return !m.empty();}
