#include "platform/RenderAPI.h"
#include "switch/render/SwitchGraphicsContext.h"
#include "switch/render/SwitchLegacyRenderer.h"
#include "switch/SwitchRuntimeDebug.h"
#include <glad/glad.h>
#include <algorithm>
#include <cstring>
#include <unordered_map>
namespace { int viewport[4]={0,0,1280,720}; }
namespace { GLenum capability(RenderCapability c){switch(c){case RenderCapability::CullFace:return GL_CULL_FACE;case RenderCapability::Blend:return GL_BLEND;case RenderCapability::DepthTest:return GL_DEPTH_TEST;case RenderCapability::PolygonOffsetFill:return GL_POLYGON_OFFSET_FILL;default:return 0;}} GLenum compare(RenderCompare c){switch(c){case RenderCompare::Never:return GL_NEVER;case RenderCompare::Less:return GL_LESS;case RenderCompare::Equal:return GL_EQUAL;case RenderCompare::LessEqual:return GL_LEQUAL;case RenderCompare::Greater:return GL_GREATER;case RenderCompare::NotEqual:return GL_NOTEQUAL;case RenderCompare::GreaterEqual:return GL_GEQUAL;case RenderCompare::Always:return GL_ALWAYS;}return GL_LESS;} GLenum blend(RenderBlendFactor f){switch(f){case RenderBlendFactor::Zero:return GL_ZERO;case RenderBlendFactor::One:return GL_ONE;case RenderBlendFactor::SrcColor:return GL_SRC_COLOR;case RenderBlendFactor::OneMinusSrcColor:return GL_ONE_MINUS_SRC_COLOR;case RenderBlendFactor::SrcAlpha:return GL_SRC_ALPHA;case RenderBlendFactor::OneMinusSrcAlpha:return GL_ONE_MINUS_SRC_ALPHA;case RenderBlendFactor::DstAlpha:return GL_DST_ALPHA;case RenderBlendFactor::OneMinusDstAlpha:return GL_ONE_MINUS_DST_ALPHA;case RenderBlendFactor::DstColor:return GL_DST_COLOR;case RenderBlendFactor::OneMinusDstColor:return GL_ONE_MINUS_DST_COLOR;}return GL_ONE;}}
void renderEnable(RenderCapability c){if(c==RenderCapability::AlphaTest){SwitchLegacyRenderer::alphaTest(true);return;}const GLenum value=capability(c);if(value)glEnable(value);} void renderDisable(RenderCapability c){if(c==RenderCapability::AlphaTest){SwitchLegacyRenderer::alphaTest(false);return;}const GLenum value=capability(c);if(value)glDisable(value);} void renderBlendFunc(RenderBlendFactor source,RenderBlendFactor dest){glBlendFunc(blend(source),blend(dest));} void renderDepthMask(bool enabled){glDepthMask(enabled?GL_TRUE:GL_FALSE);} void renderDepthFunc(RenderCompare function){glDepthFunc(compare(function));} void renderAlphaFunc(RenderCompare function,float reference){SwitchLegacyRenderer::alphaTest(true,function,reference);} void renderCullFace(RenderFace face){glCullFace(face==RenderFace::Front?GL_FRONT:face==RenderFace::Back?GL_BACK:GL_FRONT_AND_BACK);} void renderColorMask(bool r,bool g,bool b,bool a){glColorMask(r,g,b,a);} void renderBindTexture(int texture){glBindTexture(GL_TEXTURE_2D,static_cast<GLuint>(texture));} void renderSetActiveTextureUnit(int unit){glActiveTexture(GL_TEXTURE0+unit);} void renderSetClientActiveTextureUnit(int){} void renderSetMultiTextureCoord(int,float,float){} void renderSetLightmapColors(const std::uint32_t*,int){} void renderColor4f(float r,float g,float b,float a){SwitchLegacyRenderer::color(r,g,b,a);} void renderColor3f(float r,float g,float b){SwitchLegacyRenderer::color(r,g,b,1.0f);} void renderNormal3f(float,float,float){}
void renderGenerateTextures(int n,int*t){glGenTextures(n,reinterpret_cast<GLuint*>(t));} void renderDeleteTextures(int n,const int*t){glDeleteTextures(n,reinterpret_cast<const GLuint*>(t));} void renderTextureSubImageRgba(int level,int x,int y,int w,int h,const void*p){glTexSubImage2D(GL_TEXTURE_2D,level,x,y,w,h,GL_RGBA,GL_UNSIGNED_BYTE,p);} void renderTextureImageRgba(int level,int w,int h,const void*p){glTexImage2D(GL_TEXTURE_2D,level,GL_RGBA8,w,h,0,GL_RGBA,GL_UNSIGNED_BYTE,p);} void renderTextureParameters(bool blur,bool mipmaps,bool clamp){glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,mipmaps?(blur?GL_LINEAR_MIPMAP_LINEAR:GL_NEAREST_MIPMAP_LINEAR):(blur?GL_LINEAR:GL_NEAREST));glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,blur?GL_LINEAR:GL_NEAREST);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,clamp?GL_CLAMP_TO_EDGE:GL_REPEAT);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,clamp?GL_CLAMP_TO_EDGE:GL_REPEAT);}
#if PLATFORM_TEXTURE_QUALITY_CONTROLS
void renderApplyTextureQuality(bool,int,bool,int){}
#endif
int renderGetMaxAnisotropy(){return 1;} int renderGetMaxSamples(){return 1;} bool renderTextureBeginUpload(int,int,int,int,bool,bool,bool,bool){return true;} bool renderTextureIsValid(int t){return t>0;} void renderResetResources(){} void renderFogf(RenderFogParameter,float){} void renderFogi(RenderFogParameter,RenderFogMode){} void renderFogColor(const float*){} void renderLightfv(int,RenderLightParameter,const float*){} void renderLightModelAmbient(const float*){} void renderColorMaterial(RenderFace,RenderColorMaterialMode){} void renderShadeModel(RenderShadeModel){}
void renderClear(unsigned int mask){GLbitfield bits=0;if(mask&RenderClearMask::Color)bits|=GL_COLOR_BUFFER_BIT;if(mask&RenderClearMask::Depth)bits|=GL_DEPTH_BUFFER_BIT;if(bits)glClear(bits);} void renderFinishGpu(){glFinish();} void renderSubmitFrame(){glFlush();} void renderClearColor(float r,float g,float b,float a){glClearColor(r,g,b,a);} void renderClearDepth(double d){glClearDepth(d);} void renderPolygonOffset(float factor,float units){glPolygonOffset(factor,units);} void renderLineWidth(float width){glLineWidth(width);} void renderViewport(int x,int y,int w,int h){viewport[0]=x;viewport[1]=y;viewport[2]=w;viewport[3]=h;glViewport(x,y,w,h);} void renderGetViewport(int*v){glGetIntegerv(GL_VIEWPORT,v);}
void renderGetMatrix(RenderMatrixQuery q,float*v){SwitchLegacyRenderer::getMatrix(q,v);} const unsigned char* renderGetString(RenderStringQuery query){GLenum name=GL_VENDOR;if(query==RenderStringQuery::Renderer)name=GL_RENDERER;else if(query==RenderStringQuery::Version)name=GL_VERSION;else if(query==RenderStringQuery::Extensions)name=GL_EXTENSIONS;return glGetString(name);} bool renderSupportsFeature(RenderFeature){return false;} unsigned int renderGetError(){return glGetError();} void renderFogHint(RenderHintMode){} void renderMatrixMode(RenderMatrixMode m){SwitchLegacyRenderer::matrixMode(m);} void renderLoadIdentity(){SwitchLegacyRenderer::loadIdentity();} void renderPushMatrix(){SwitchLegacyRenderer::pushMatrix();} void renderPopMatrix(){SwitchLegacyRenderer::popMatrix();} void renderTranslate(float x,float y,float z){SwitchLegacyRenderer::translate(x,y,z);} void renderRotate(float a,float x,float y,float z){SwitchLegacyRenderer::rotate(a,x,y,z);} void renderScale(float x,float y,float z){SwitchLegacyRenderer::scale(x,y,z);} void renderScaleDouble(double x,double y,double z){SwitchLegacyRenderer::scale(x,y,z);} void renderFrustum(double l,double r,double b,double t,double n,double f){SwitchLegacyRenderer::frustum(l,r,b,t,n,f);} void renderOrtho(double l,double r,double b,double t,double n,double f){SwitchLegacyRenderer::ortho(l,r,b,t,n,f);}
bool renderCopyFramebufferToBoundTexture(int x,int y,int w,int h){if(w<=0||h<=0)return false;glCopyTexSubImage2D(GL_TEXTURE_2D,0,0,0,x,y,w,h);return glGetError()==GL_NO_ERROR;} void renderSetLegacyPresentationGamma(bool){}
namespace { std::unordered_map<int,RenderCapturedMesh> displayLists; int compilingList=0; }
bool renderCaptureInterleaved(const RenderInterleavedMesh&m,RenderCapturedMesh&o,bool append){if(!m.data||m.count<=0||m.stride<=0)return false;if(!append)o.clear();if(!o.empty()&&(o.stride!=m.stride||o.primitive!=m.primitive))return false;o.stride=m.stride;o.primitive=m.primitive;o.positionShort=m.positionShort;o.hasTexture=m.hasTexture;o.texCoordOffset=m.texCoordOffset;o.hasColor=m.hasColor;o.colorOffset=m.colorOffset;o.hasNormals=m.hasNormals;o.normalOffset=m.normalOffset;o.hasBrightness=m.hasBrightness;o.brightnessOffset=m.brightnessOffset;const auto*src=static_cast<const unsigned char*>(m.data)+(std::size_t)m.first*m.stride;const std::size_t bytes=(std::size_t)m.count*m.stride;const std::size_t old=o.raw.size();o.raw.resize(old+(bytes+3)/4);std::memcpy(reinterpret_cast<unsigned char*>(o.raw.data())+old*4,src,bytes);o.vertexCount+=m.count;return true;}
bool renderDrawInterleaved(const RenderInterleavedMesh&m){if(compilingList)return renderCaptureInterleaved(m,displayLists[compilingList],true);return SwitchLegacyRenderer::draw(m);} bool renderDrawCaptured(const RenderCapturedMesh&m){if(m.empty())return false;RenderInterleavedMesh view;view.data=m.raw.data();view.stride=m.stride;view.count=m.vertexCount;view.primitive=m.primitive;view.positionShort=m.positionShort;view.hasTexture=m.hasTexture;view.texCoordOffset=m.texCoordOffset;view.hasColor=m.hasColor;view.colorOffset=m.colorOffset;view.hasNormals=m.hasNormals;view.normalOffset=m.normalOffset;view.hasBrightness=m.hasBrightness;view.brightnessOffset=m.brightnessOffset;return renderDrawInterleaved(view);}

// The shared renderer still uses legacy retained handles for sky and chunk
// bookkeeping. Keep a handle namespace until the Switch terrain renderer owns
// those meshes directly; no desktop GL implementation is pulled into the NRO.
namespace { int nextDisplayList = 1; int nextQuery = 1; }
int renderGenerateDisplayLists(int count){const int first=nextDisplayList;nextDisplayList+=count;return first;}
void renderDeleteDisplayLists(int first,int count){for(int i=0;i<count;++i)displayLists.erase(first+i);} void renderBeginDisplayList(int list){compilingList=list;displayLists[list].clear();} void renderEndDisplayList(){compilingList=0;}
void renderCallDisplayList(int list)
{
    const auto found = displayLists.find(list);
    if (found == displayLists.end())
    {
        switchDebugDisplayListResult(false, false, 0);
        return;
    }
    const bool drawn = renderDrawCaptured(found->second);
    switchDebugDisplayListResult(true, drawn, found->second.vertexCount);
}
void renderCallDisplayLists(int count,const int*lists){for(int i=0;i<count;++i)renderCallDisplayList(lists[i]);}
void renderGenerateOcclusionQueries(int count,int* queries){while(count--)*queries++=nextQuery++;}
void renderBeginOcclusionQuery(int){} void renderEndOcclusionQuery(){}
bool renderOcclusionQueryResultAvailable(int){return true;} unsigned int renderOcclusionQueryResult(int){return 1;}
bool renderReadPixelsRgb(int x,int y,int w,int h,void*p){if(!p||w<=0||h<=0)return false;glPixelStorei(GL_PACK_ALIGNMENT,1);glReadPixels(x,y,w,h,GL_RGB,GL_UNSIGNED_BYTE,p);return glGetError()==GL_NO_ERROR;}
